import type { TicketSeed } from "./tickets";

/**
 * Twenty more tickets in the signed-in agent's queue, so the ticket listing
 * and its workspace can be tried against a realistic volume. They exist only
 * for the listing: the Overview leaves them out (see LISTING_ONLY_TICKET_IDS),
 * so its counts, widgets and statistics are unaffected.
 *
 * Times are minutes ago (`ago`) or minutes from now (`frDueIn` / `resDueIn`).
 */
const H = 60;
const D = 24 * H;

export const LISTING_TICKET_SEEDS: TicketSeed[] = [
  {
    n: 483,
    subject: "Payment failed for order #4821",
    contact: "con-marcus",
    assignee: "agt-sarah",
    team: "team-billing",
    status: "open",
    priority: "urgent",
    type: "incident",
    category: "billing",
    source: "email",
    tags: ["billing", "payment"],
    frDueIn: 18,
    thread: [
      {
        ago: 12,
        from: "c",
        body: "Hi,\n\nThe payment went through but I'm still seeing an error on my order. Can you please check and confirm if the payment was successful?\n\nOrder ID: #4821\n\nThanks,\nMarcus",
      },
      { ago: 8, from: "n:agt-alex", body: "Customer says payment was successful but the order wasn't updated. Checking the gateway logs now." },
    ],
  },
  {
    n: 484,
    subject: "Unable to reset password",
    contact: "con-priya",
    assignee: "agt-sarah",
    team: "team-tech",
    status: "open",
    priority: "high",
    type: "question",
    category: "account",
    source: "email",
    tags: ["login", "password"],
    frDueIn: 42,
    thread: [
      { ago: 34, from: "c", body: "I've tried the reset link multiple times but it says the link has expired every time I open it. Can you help?" },
    ],
  },
  {
    n: 485,
    subject: "Invoice not received",
    contact: "con-jwilson",
    assignee: "agt-sarah",
    team: "team-billing",
    status: "open",
    priority: "high",
    type: "question",
    category: "billing",
    source: "web_form",
    tags: ["billing", "invoice"],
    frDueIn: 2 * H,
    thread: [
      { ago: 1 * H, from: "c", body: "I haven't received my invoice for the last month. Can you resend it to finance@cedarfinance.example as well?" },
    ],
  },
  {
    n: 486,
    subject: "Update shipping address",
    contact: "con-tom",
    assignee: "agt-sarah",
    team: "team-success",
    status: "pending",
    priority: "medium",
    type: "task",
    category: "general",
    source: "chat",
    tags: ["follow-up"],
    thread: [
      { ago: 3 * H, from: "c", body: "Can you please update my shipping address to 123 Main Street, Springfield before the next delivery?" },
      { ago: 2 * H, from: "a:agt-sarah", body: "Happy to help, Tom. Could you confirm the ZIP code and whether this applies to all future orders?" },
    ],
  },
  {
    n: 487,
    subject: "Feature request: bulk export",
    contact: "con-rachel",
    assignee: "agt-sarah",
    team: "team-integrations",
    status: "open",
    priority: "low",
    type: "feature_request",
    category: "product",
    source: "chat",
    tags: ["feature-request", "export"],
    frDueIn: 4 * H,
    thread: [
      { ago: 3 * H, from: "c", body: "It would be great to have a bulk export option for orders. Right now we export each store separately." },
    ],
  },
  {
    n: 488,
    subject: "Error while exporting report",
    contact: "con-dbrooks",
    assignee: "agt-sarah",
    team: "team-tech",
    status: "open",
    priority: "medium",
    type: "incident",
    category: "reporting",
    source: "email",
    tags: ["reporting", "export"],
    frDueIn: 6 * H,
    thread: [
      { ago: 5 * H, from: "c", body: "Getting an error when I try to export the quarterly shipments report: \"Export failed (code 504)\". Smaller date ranges work." },
    ],
  },
  {
    n: 489,
    subject: "Subscription renewal query",
    contact: "con-grace",
    assignee: "agt-sarah",
    team: "team-sales",
    status: "open",
    priority: "low",
    type: "question",
    category: "billing",
    source: "phone",
    tags: ["billing"],
    frDueIn: 8 * H,
    thread: [
      { ago: 5 * H, from: "c", body: "Phone call: Grace asked whether there are discounts for switching to annual billing at renewal next month." },
    ],
  },
  {
    n: 490,
    subject: "Login issue on mobile app",
    contact: "con-sophia",
    assignee: "agt-sarah",
    team: "team-tech",
    status: "open",
    priority: "medium",
    type: "problem",
    category: "account",
    source: "chat",
    tags: ["login", "mobile"],
    resDueIn: 1 * D,
    thread: [
      { ago: 6 * H, from: "c", body: "I'm unable to log in to the mobile app. It keeps returning to the sign-in screen after I enter my code." },
      { ago: 5 * H + 30, from: "a:agt-sarah", body: "Thanks Sophia — could you tell me the app version (Settings → About) and whether you're on iOS or Android?" },
      { ago: 4 * H, from: "c", body: "iOS, version 5.2.1. Reinstalling didn't help." },
    ],
  },
  {
    n: 491,
    subject: "API rate limit exceeded",
    contact: "con-aaron",
    assignee: "agt-sarah",
    team: "team-integrations",
    status: "open",
    priority: "high",
    type: "incident",
    category: "integration",
    source: "api",
    tags: ["api"],
    resDueIn: 1 * D,
    thread: [
      { ago: 8 * H, from: "c", body: "We're getting 429 errors on the API endpoint /v2/patients since this morning, well below our documented limit." },
      { ago: 7 * H, from: "a:agt-sarah", body: "I've asked our platform team to check your rate-limit bucket. Could you share a request ID from one of the failed calls?" },
      { ago: 6 * H, from: "n:agt-james", body: "Their key is on the legacy 60 rpm tier — needs migrating to the new plan limits." },
    ],
  },
  {
    n: 492,
    subject: "Request for data deletion",
    contact: "con-ravi",
    assignee: "agt-sarah",
    team: "team-success",
    status: "open",
    priority: "medium",
    type: "task",
    category: "security",
    source: "web_form",
    tags: ["data-quality"],
    resDueIn: 2 * D,
    thread: [
      { ago: 1 * D, from: "c", body: "I would like to request deletion of my personal data under GDPR. Please confirm once this is done." },
      { ago: 22 * H, from: "a:agt-sarah", body: "We've received your request, Ravi. We'll verify your identity by email and complete the deletion within 30 days." },
    ],
  },
  {
    n: 493,
    subject: "Duplicate charge on credit card",
    contact: "con-marcus",
    assignee: "agt-sarah",
    team: "team-billing",
    status: "open",
    priority: "high",
    type: "problem",
    category: "billing",
    source: "email",
    tags: ["billing", "refund"],
    frDueIn: -25,
    thread: [
      { ago: 1 * H + 25, from: "c", body: "We were charged twice for invoice INV-20931 this morning. Please refund the duplicate payment." },
    ],
  },
  {
    n: 494,
    subject: "Webhook deliveries failing",
    contact: "con-laura",
    assignee: "agt-sarah",
    team: "team-integrations",
    status: "on_hold",
    priority: "high",
    type: "incident",
    category: "integration",
    source: "portal",
    tags: ["api", "customer-impact"],
    thread: [
      { ago: 2 * D, from: "c", body: "Our webhook endpoint stopped receiving order.created events yesterday. Nothing changed on our side." },
      { ago: 2 * D - 2 * H, from: "a:agt-sarah", body: "Thanks Laura. I can see deliveries are returning TLS errors. I've raised this with engineering and will update you." },
      { ago: 1 * D, from: "n:agt-sarah", body: "On hold until the certificate rotation fix ships (ENG-2211)." },
    ],
    events: [{ ago: 1 * D, type: "status_changed", description: "Status changed from Open to On Hold", actor: "Sarah Wilson" }],
  },
  {
    n: 495,
    subject: "Add new users to workspace",
    contact: "con-hannah",
    assignee: "agt-sarah",
    team: "team-success",
    status: "pending",
    priority: "low",
    type: "task",
    category: "account",
    source: "email",
    tags: ["follow-up"],
    thread: [
      { ago: 1 * D + 4 * H, from: "c", body: "Can you add three new coordinators to our workspace? Names and emails attached.", files: [["new-users.csv", 2_048, "text/csv"]] },
      { ago: 1 * D, from: "a:agt-sarah", body: "Done — invitations are on their way. Could you let me know which team each person should join?" },
    ],
  },
  {
    n: 496,
    subject: "Dashboard loading slowly",
    contact: "con-sophia",
    assignee: "agt-sarah",
    team: "team-tech",
    status: "open",
    priority: "medium",
    type: "problem",
    category: "technical",
    source: "web_form",
    tags: ["performance"],
    frDueIn: 3 * H,
    thread: [
      { ago: 55, from: "c", body: "The main dashboard takes 20–30 seconds to load since the last update. Other pages are fine." },
    ],
  },
  {
    n: 497,
    subject: "Two users locked out after SSO change",
    contact: "con-aaron",
    assignee: "agt-sarah",
    team: "team-tech",
    status: "open",
    priority: "urgent",
    type: "incident",
    category: "security",
    source: "phone",
    tags: ["login", "sso", "customer-impact"],
    frDueIn: 9,
    thread: [
      { ago: 21, from: "c", body: "Phone call: after switching identity providers, two clinicians can't sign in and are being sent to an error page." },
    ],
  },
  {
    n: 498,
    subject: "Wrong tax rate on latest invoice",
    contact: "con-jwilson",
    assignee: "agt-sarah",
    team: "team-billing",
    status: "open",
    priority: "medium",
    type: "problem",
    category: "billing",
    source: "email",
    tags: ["billing", "invoice"],
    resDueIn: 2 * D + 6 * H,
    thread: [
      { ago: 1 * D + 6 * H, from: "c", body: "Our latest invoice applies 20% VAT, but we're exempt. Our VAT number is on the account." },
      { ago: 1 * D + 2 * H, from: "a:agt-sarah", body: "Thanks James — I'm checking with our billing team why the exemption wasn't applied and will reissue the invoice." },
      { ago: 3 * H, from: "c", body: "Any update on this? Our month-end close is on Friday." },
    ],
  },
  {
    n: 499,
    subject: "How do I set up two-factor authentication?",
    contact: "con-michael",
    assignee: "agt-sarah",
    team: "team-tech",
    status: "open",
    priority: "low",
    type: "question",
    category: "security",
    source: "chat",
    tags: ["security"],
    frDueIn: 7 * H,
    thread: [{ ago: 40, from: "c", body: "Our security team wants everyone on two-factor. Where do I turn it on for my account?" }],
  },
  {
    n: 500,
    subject: "CSV upload stuck at 99%",
    contact: "con-hannah",
    assignee: "agt-sarah",
    team: "team-tech",
    status: "open",
    priority: "high",
    type: "incident",
    category: "technical",
    source: "email",
    tags: ["import", "csv"],
    frDueIn: 33,
    thread: [
      {
        ago: 27,
        from: "c",
        body: "Our shipment CSV upload has been stuck at 99% for half an hour. The file is about 40 MB.",
        files: [["upload-progress.png", 412_000, "image/png"]],
      },
    ],
  },
  {
    n: 501,
    subject: "Cancel add-on before renewal",
    contact: "con-rachel",
    assignee: "agt-sarah",
    team: "team-sales",
    status: "pending",
    priority: "medium",
    type: "task",
    category: "billing",
    source: "social",
    tags: ["billing", "seats"],
    thread: [
      { ago: 2 * D + 3 * H, from: "c", body: "Please cancel the analytics add-on before our renewal on the 15th. We no longer use it." },
      { ago: 2 * D, from: "a:agt-sarah", body: "I can do that, Rachel. Just to confirm — should the add-on end at renewal, or would you like it removed today?" },
    ],
  },
  {
    n: 502,
    subject: "Scheduled report sent to wrong recipients",
    contact: "con-laura",
    assignee: "agt-sarah",
    team: "team-tech",
    status: "open",
    priority: "medium",
    type: "problem",
    category: "reporting",
    source: "portal",
    tags: ["reporting", "scheduled"],
    resDueIn: 1 * D + 18 * H,
    thread: [
      { ago: 1 * D + 2 * H, from: "c", body: "Our weekly plant report went to a distribution list we removed last month." },
      { ago: 1 * D, from: "a:agt-sarah", body: "Sorry about that, Laura. The schedule still had the old list cached — I've cleared it. Next run is Monday 7:00 AM." },
      { ago: 2 * H, from: "c", body: "Thanks. Can you confirm who will receive the next one?" },
    ],
  },
];
